# make use of vm's 
sudo: 'required'

# have the docker service set up (we'll
# update it later)
services:
  - 'docker'

# prepare the machine before any code
# installation scripts
before_install:
  - './.travis/prepare.sh'

# make docker image
script:
  - if [[ "${TRAVIS_BRANCH,,}" == "master" ]]; then
      make build ;
    elif [[ "${TRAVIS_BRANCH,,}" == *"-rc"* ]]; then
      make build -e VERSION="rc" ;
    else
      make build -e VERSION="${TRAVIS_BRANCH,,}" ;
    fi

# only execute the following instructions in
# the case of a success (failing at this point
# won't mark the build as a failure).
# To have `DOCKER_USERNAME` and `DOCKER_PASSWORD`
# filled you need to either use `travis`' cli 
# and then `travis set ..` or go to the travis
# page of your repository and then change the 
# environment in the settings pannel.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ;
  - if [[ "${TRAVIS_BRANCH,,}" == "master" ]]; then
      make push ;
    elif [[ "${TRAVIS_BRANCH,,}" == *"-rc"* ]]; then
      make push -e VERSION="rc" ;
    else
      make push -e VERSION="${TRAVIS_BRANCH,,}" ;
    fi

# don't notify me when things fail
notifications:
  email: false
